In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

path_=r"C:\Users\devan\OneDrive\Desktop\End-to-End-Pipeline\Used_Car_Prices.csv"

df=pd.read_csv(path_)

In [3]:
df

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [29]:
df.isnull().sum()

brand            0
km_driven        0
fuel             0
owner            0
selling_price    0
dtype: int64

In [4]:
df.drop_duplicates(inplace=True)

In [5]:
df['brand'].value_counts().sort_values(ascending=False).head(5)

brand
Maruti      1954
Hyundai     1176
Mahindra     648
Tata         599
Honda        354
Name: count, dtype: int64

In [6]:
lis=['Maruti','Hyundai','Mahindra','Tata']

In [7]:
df['brand']=df['brand'].apply( lambda x: x if x in lis else 'Others' )

In [8]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

df['brand'] = encoder.fit_transform(df['brand'])

In [9]:
(df['brand'].value_counts()/df['brand'].value_counts().sum())*100

brand
3    32.139535
2    30.294574
0    18.232558
1    10.046512
4     9.286822
Name: count, dtype: float64

In [10]:
df['fuel'].unique()

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [11]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth & Above Owner', 'Test Drive Car'], dtype=object)

In [16]:
from sklearn.preprocessing import OneHotEncoder
one_enc=OneHotEncoder(sparse_output=False,handle_unknown='ignore')
p=one_enc.fit_transform(df[['fuel','owner']])

In [22]:
p[0]

array([0., 1., 0., 0., 1., 0., 0., 0., 0.])

In [20]:
k=pd.DataFrame(p)
k

        0    1    2    3    4    5    6    7    8
0     0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
1     0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
2     0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0
3     0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
4     0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...
6445  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0
6446  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
6447  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0
6448  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
6449  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0

[6450 rows x 9 columns]

In [ ]:
df.drop(columns=['fuel','owner'],inplace=True)

In [27]:
df

      brand  km_driven  selling_price
0         2     145500         450000
1         3     120000         370000
2         3     140000         158000
3         0     127000         225000
4         2     120000         130000
...     ...        ...            ...
8121      2      50000         260000
8122      0      80000         475000
8123      0     110000         320000
8124      0     119000         135000
8125      2     120000         382000

[6450 rows x 3 columns]

In [37]:
pd.concat([df,k],axis=1)

,brand,km_driven,selling_price,0,1,2,3,4,5,6,7,8
0,2.0,145500.0,450000.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,3.0,120000.0,370000.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,3.0,140000.0,158000.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,0.0,127000.0,225000.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,2.0,120000.0,130000.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6404,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6423,NaN,NaN,NaN,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
6426,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6437,NaN,NaN,NaN,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
6447,NaN,NaN,NaN,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0